author: LPkkjHD
name: ${project.artifactId}
version: ${project.version}
website: http://freemine.de/
main: de.freemine.permissioneffects.Main
depends: [helper]
commands:
  PermissionEffects:
    aliases: [pe]
    permission: pe.admin
  ToggleEffects:
    aliases: [te,toggle,togglee,teffects]
    permission: pe.toggle
