author: LPkkjHD
authors: [LPkkjHD, stefan01, bigibas123]
name: ${project.artifactId}
version: ${project.version}
website: http://freemine.de/
main: de.freemine.permissioneffects.Main
depend: [helper]
commands:
  PermissionEffects:
    aliases: [pe]
    permission: pe.admin
  ToggleEffects:
    aliases: [te,toggle,togglee,teffects]
    permission: pe.toggle
